import { MemoryRecordSchema, memoryCategories, type MemoryRecord } from "./schema.js";
import type { RuntimeEnv } from "../../config/env.js";

export type SupabaseMemoryFetch = (url: string, init: RequestInit) => Promise<Response>;

export interface SupabaseMemoryRepository {
  append(record: MemoryRecord): Promise<MemoryRecord>;
  list(scope: string): Promise<MemoryRecord[]>;
  listAll(): Promise<MemoryRecord[]>;
}

export interface SupabaseMemoryRepositoryOptions {
  fetcher?: SupabaseMemoryFetch;
  serviceRoleKey: string;
  tableName?: string;
  url: string;
}

interface SupabaseMemoryRow {
  category: string;
  created_at: string;
  id: string;
  payload_json: Record<string, unknown> | string;
  record_ids_json: string[] | string;
  scope: string;
  trust_level: string;
}

const defaultMemoryTableName = "recoup_memory_records";

export function createSupabaseMemoryRepository(options: SupabaseMemoryRepositoryOptions): SupabaseMemoryRepository {
  const tableName = normalizeTableName(options.tableName ?? defaultMemoryTableName);
  const baseUrl = normalizeSupabaseUrl(options.url);
  const fetcher = options.fetcher ?? fetch;

  return {
    async append(record) {
      const parsed = MemoryRecordSchema.parse(record);
      const rows = await requestRows(fetcher, {
        body: JSON.stringify(toSupabaseRow(parsed)),
        method: "POST",
        serviceRoleKey: options.serviceRoleKey,
        url: `${baseUrl}/rest/v1/${tableName}?on_conflict=id`
      });

      return parseSupabaseMemoryRow(rows[0]);
    },
    async list(scope) {
      const url = new URL(`${baseUrl}/rest/v1/${tableName}`);
      url.searchParams.set("scope", `eq.${scope}`);
      url.searchParams.set("order", "sequence.asc");
      return (await requestRows(fetcher, { method: "GET", serviceRoleKey: options.serviceRoleKey, url: url.href })).map(
        parseSupabaseMemoryRow
      );
    },
    async listAll() {
      const url = new URL(`${baseUrl}/rest/v1/${tableName}`);
      url.searchParams.set("order", "sequence.asc");
      return (await requestRows(fetcher, { method: "GET", serviceRoleKey: options.serviceRoleKey, url: url.href })).map(
        parseSupabaseMemoryRow
      );
    }
  };
}

export function createSupabaseMemoryRepositoryFromEnv(
  env: RuntimeEnv,
  fetcher?: SupabaseMemoryFetch
): SupabaseMemoryRepository | undefined {
  if (env.SUPABASE_SERVICE_ROLE_KEY === undefined || env.SUPABASE_URL === undefined) {
    return undefined;
  }

  return createSupabaseMemoryRepository({
    ...(fetcher === undefined ? {} : { fetcher }),
    serviceRoleKey: env.SUPABASE_SERVICE_ROLE_KEY,
    ...(env.RECOUP_SUPABASE_MEMORY_TABLE === undefined ? {} : { tableName: env.RECOUP_SUPABASE_MEMORY_TABLE }),
    url: env.SUPABASE_URL
  });
}

export function buildSupabaseMemorySchemaSql(tableName = defaultMemoryTableName): string {
  const safeTableName = normalizeTableName(tableName);
  const categoryValues = memoryCategories.map((category) => `'${category}'`).join(", ");
  return `
CREATE TABLE IF NOT EXISTS recoup_app_principals (
  principal text PRIMARY KEY,
  capabilities text[] NOT NULL DEFAULT ARRAY[]::text[],
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ${safeTableName} (
  sequence bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id text NOT NULL,
  category text NOT NULL CHECK (category IN (${categoryValues})),
  trust_level text NOT NULL CHECK (trust_level IN ('trusted', 'semi_trusted', 'untrusted')),
  scope text NOT NULL,
  payload_json jsonb NOT NULL CHECK (jsonb_typeof(payload_json) = 'object'),
  record_ids_json jsonb NOT NULL CHECK (jsonb_typeof(record_ids_json) = 'array' AND jsonb_array_length(record_ids_json) > 0),
  created_at timestamptz NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_${safeTableName}_id ON ${safeTableName} (id);
CREATE INDEX IF NOT EXISTS idx_${safeTableName}_scope_sequence ON ${safeTableName} (scope, sequence);
CREATE INDEX IF NOT EXISTS idx_${safeTableName}_record_ids ON ${safeTableName} USING gin (record_ids_json);
CREATE INDEX IF NOT EXISTS idx_recoup_app_principals_capabilities ON recoup_app_principals USING gin (capabilities);

REVOKE ALL ON TABLE ${safeTableName} FROM anon, authenticated;
REVOKE ALL ON TABLE recoup_app_principals FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON TABLE ${safeTableName} TO service_role;
GRANT SELECT, INSERT, UPDATE ON TABLE recoup_app_principals TO service_role;

ALTER TABLE recoup_app_principals ENABLE ROW LEVEL SECURITY;
ALTER TABLE recoup_app_principals FORCE ROW LEVEL SECURITY;
ALTER TABLE ${safeTableName} ENABLE ROW LEVEL SECURITY;
ALTER TABLE ${safeTableName} FORCE ROW LEVEL SECURITY;
`.trim();
}

async function requestRows(
  fetcher: SupabaseMemoryFetch,
  input: { body?: string; method: "GET" | "POST"; serviceRoleKey: string; url: string }
): Promise<SupabaseMemoryRow[]> {
  const response = await fetcher(input.url, {
    ...(input.body === undefined ? {} : { body: input.body }),
    headers: {
      apikey: input.serviceRoleKey,
      authorization: `Bearer ${input.serviceRoleKey}`,
      "content-type": "application/json",
      prefer: "resolution=merge-duplicates,return=representation"
    },
    method: input.method
  });

  if (!response.ok) {
    throw new Error(`Supabase memory request failed with HTTP ${String(response.status)}.`);
  }

  return (await response.json()) as SupabaseMemoryRow[];
}

function toSupabaseRow(record: MemoryRecord): SupabaseMemoryRow {
  return {
    category: record.category,
    created_at: record.createdAt,
    id: record.id,
    payload_json: record.payload,
    record_ids_json: record.recordIds,
    scope: record.scope,
    trust_level: record.trustLevel
  };
}

function parseSupabaseMemoryRow(row: SupabaseMemoryRow | undefined): MemoryRecord {
  if (row === undefined) {
    throw new Error("Supabase memory response did not include a record.");
  }

  return MemoryRecordSchema.parse({
    category: row.category,
    createdAt: normalizeSupabaseTimestamp(row.created_at),
    id: row.id,
    payload: parseJsonCell(row.payload_json),
    recordIds: parseJsonCell(row.record_ids_json),
    scope: row.scope,
    trustLevel: row.trust_level
  });
}

function parseJsonCell(value: Record<string, unknown> | string | string[]): unknown {
  return typeof value === "string" ? (JSON.parse(value) as unknown) : value;
}

function normalizeSupabaseTimestamp(value: string): string {
  const parsed = new Date(value);
  if (!Number.isNaN(parsed.valueOf())) {
    return parsed.toISOString();
  }

  const postgresTimestamp = /^(\d{4}-\d{2}-\d{2})[ T](\d{2}:\d{2}:\d{2})(\.\d+)?([+-]\d{2})(?::?(\d{2}))?$/u.exec(
    value
  );
  if (postgresTimestamp === null) {
    return value;
  }

  const date = postgresTimestamp[1];
  const time = postgresTimestamp[2];
  const offsetHours = postgresTimestamp[4];
  if (date === undefined || time === undefined || offsetHours === undefined) {
    return value;
  }

  const fraction = postgresTimestamp[3] === undefined ? ".000" : postgresTimestamp[3].slice(0, 4).padEnd(4, "0");
  const offsetMinutes = postgresTimestamp[5] ?? "00";
  const normalized = `${date}T${time}${fraction}${offsetHours}:${offsetMinutes}`;
  const normalizedDate = new Date(normalized);

  return Number.isNaN(normalizedDate.valueOf()) ? value : normalizedDate.toISOString();
}

function normalizeSupabaseUrl(url: string): string {
  return url.replace(/\/+$/u, "");
}

function normalizeTableName(tableName: string): string {
  if (!/^[a-z][a-z0-9_]*$/u.test(tableName)) {
    throw new Error("Supabase memory table name must be a safe Postgres identifier.");
  }

  return tableName;
}
