CREATE TABLE IF NOT EXISTS recoup_app_principals (
  principal text PRIMARY KEY,
  capabilities text[] NOT NULL DEFAULT ARRAY[]::text[],
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS recoup_memory_records (
  sequence bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id text NOT NULL,
  category text NOT NULL CHECK (category IN ('session_state', 'workflow_state', 'case_state', 'transaction_state', 'evidence_refs', 'approval_records', 'audit_refs', 'connector_state', 'compaction_summaries', 'artifact_refs', 'agent_handoff_packets')),
  trust_level text NOT NULL CHECK (trust_level IN ('trusted', 'semi_trusted', 'untrusted')),
  scope text NOT NULL,
  payload_json jsonb NOT NULL CHECK (jsonb_typeof(payload_json) = 'object'),
  record_ids_json jsonb NOT NULL CHECK (jsonb_typeof(record_ids_json) = 'array' AND jsonb_array_length(record_ids_json) > 0),
  created_at timestamptz NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_recoup_memory_records_id ON recoup_memory_records (id);
CREATE INDEX IF NOT EXISTS idx_recoup_memory_records_scope_sequence ON recoup_memory_records (scope, sequence);
CREATE INDEX IF NOT EXISTS idx_recoup_memory_records_record_ids ON recoup_memory_records USING gin (record_ids_json);
CREATE INDEX IF NOT EXISTS idx_recoup_app_principals_capabilities ON recoup_app_principals USING gin (capabilities);

REVOKE ALL ON TABLE recoup_memory_records FROM anon, authenticated;
REVOKE ALL ON TABLE recoup_app_principals FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON TABLE recoup_memory_records TO service_role;
GRANT SELECT, INSERT, UPDATE ON TABLE recoup_app_principals TO service_role;

ALTER TABLE recoup_app_principals ENABLE ROW LEVEL SECURITY;
ALTER TABLE recoup_app_principals FORCE ROW LEVEL SECURITY;
ALTER TABLE recoup_memory_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE recoup_memory_records FORCE ROW LEVEL SECURITY;
