CREATE TABLE IF NOT EXISTS recoup_app_principals (
  principal text PRIMARY KEY,
  capabilities text[] NOT NULL DEFAULT ARRAY[]::text[],
  created_at timestamptz NOT NULL DEFAULT now()
);

DROP INDEX IF EXISTS idx_recoup_config_active_key;

CREATE TABLE IF NOT EXISTS recoup_config (
  config_version int NOT NULL,
  key text NOT NULL CHECK (key IN ('arbitration_weights', 'r_score_weights', 'r_drift', 'gaming_gate', 'partial_hold', 'accuracy_bars', 'seed')),
  value_json jsonb NOT NULL CHECK (jsonb_typeof(value_json) = 'object'),
  config_hash text NOT NULL CHECK (config_hash ~ '^[a-f0-9]{64}$'),
  effective_from timestamptz NOT NULL,
  approved_by text NOT NULL REFERENCES recoup_app_principals(principal),
  active boolean NOT NULL DEFAULT true,
  PRIMARY KEY (config_version, key)
);

CREATE TABLE IF NOT EXISTS recoup_audit_chain (
  entry_hash text PRIMARY KEY CHECK (entry_hash ~ '^[a-f0-9]{64}$'),
  prev_hash text CHECK (prev_hash IS NULL OR prev_hash ~ '^[a-f0-9]{64}$'),
  payload jsonb NOT NULL CHECK (jsonb_typeof(payload) = 'object'),
  seq bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS recoup_src_bureau (
  customer_id text NOT NULL,
  bureau_id text PRIMARY KEY,
  as_of_date date NOT NULL,
  risk_score int NOT NULL CHECK (risk_score >= 0 AND risk_score <= 100),
  limit_recommendation numeric NOT NULL,
  public_records jsonb NOT NULL CHECK (jsonb_typeof(public_records) = 'object'),
  delinquency_flag boolean NOT NULL,
  provenance text NOT NULL CHECK (provenance = 'synthetic')
);

CREATE TABLE IF NOT EXISTS recoup_src_docs (
  doc_id text PRIMARY KEY,
  doc_type text NOT NULL CHECK (doc_type IN ('POD', 'contract', 'TPM', 'correspondence')),
  customer_id text NOT NULL,
  linked_record_ids jsonb NOT NULL CHECK (jsonb_typeof(linked_record_ids) = 'array' AND jsonb_array_length(linked_record_ids) > 0),
  uri text NOT NULL,
  signed_date date,
  provenance text NOT NULL CHECK (provenance = 'synthetic')
);

CREATE TABLE IF NOT EXISTS recoup_src_remittance (
  remit_id text PRIMARY KEY,
  transaction_set text NOT NULL CHECK (transaction_set IN ('820', '812', '810', 'manual')),
  customer_id text NOT NULL,
  paid_amount numeric NOT NULL,
  invoice_refs jsonb NOT NULL CHECK (jsonb_typeof(invoice_refs) = 'array'),
  deduction_refs jsonb NOT NULL CHECK (jsonb_typeof(deduction_refs) = 'array'),
  payment_date date NOT NULL,
  currency text NOT NULL,
  provenance text NOT NULL CHECK (provenance = 'synthetic')
);

CREATE TABLE IF NOT EXISTS recoup_src_tpm (
  promo_id text PRIMARY KEY,
  customer_id text NOT NULL,
  product_scope jsonb NOT NULL CHECK (jsonb_typeof(product_scope) = 'object'),
  promo_type text NOT NULL,
  approved_allowance numeric NOT NULL,
  accrued_amount numeric NOT NULL,
  window_start date NOT NULL,
  window_end date NOT NULL,
  claim_refs jsonb NOT NULL CHECK (jsonb_typeof(claim_refs) = 'array'),
  provenance text NOT NULL CHECK (provenance = 'synthetic'),
  CHECK (window_end >= window_start)
);

CREATE TABLE IF NOT EXISTS recoup_memory_records (
  sequence bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id text NOT NULL,
  category text NOT NULL CHECK (category IN ('session_state', 'workflow_state', 'case_state', 'transaction_state', 'evidence_refs', 'approval_records', 'audit_refs', 'connector_state', 'compaction_summaries', 'artifact_refs', 'agent_handoff_packets')),
  trust_level text NOT NULL CHECK (trust_level IN ('trusted', 'semi_trusted', 'untrusted')),
  scope text NOT NULL,
  payload_json jsonb NOT NULL CHECK (jsonb_typeof(payload_json) = 'object'),
  record_ids_json jsonb NOT NULL CHECK (jsonb_typeof(record_ids_json) = 'array' AND jsonb_array_length(record_ids_json) > 0),
  created_at timestamptz NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_recoup_config_version ON recoup_config (config_version);
CREATE UNIQUE INDEX IF NOT EXISTS idx_recoup_audit_chain_seq ON recoup_audit_chain (seq);
CREATE INDEX IF NOT EXISTS idx_recoup_src_bureau_customer_date ON recoup_src_bureau (customer_id, as_of_date);
CREATE INDEX IF NOT EXISTS idx_recoup_src_docs_customer ON recoup_src_docs (customer_id);
CREATE INDEX IF NOT EXISTS idx_recoup_src_docs_linked_record_ids ON recoup_src_docs USING gin (linked_record_ids);
CREATE INDEX IF NOT EXISTS idx_recoup_src_remittance_customer_payment ON recoup_src_remittance (customer_id, payment_date);
CREATE INDEX IF NOT EXISTS idx_recoup_src_remittance_invoice_refs ON recoup_src_remittance USING gin (invoice_refs);
CREATE INDEX IF NOT EXISTS idx_recoup_src_remittance_deduction_refs ON recoup_src_remittance USING gin (deduction_refs);
CREATE INDEX IF NOT EXISTS idx_recoup_src_tpm_customer_window ON recoup_src_tpm (customer_id, window_start, window_end);
CREATE INDEX IF NOT EXISTS idx_recoup_src_tpm_claim_refs ON recoup_src_tpm USING gin (claim_refs);
CREATE UNIQUE INDEX IF NOT EXISTS idx_recoup_memory_records_id ON recoup_memory_records (id);
CREATE INDEX IF NOT EXISTS idx_recoup_memory_records_scope_sequence ON recoup_memory_records (scope, sequence);
CREATE INDEX IF NOT EXISTS idx_recoup_memory_records_record_ids ON recoup_memory_records USING gin (record_ids_json);
CREATE INDEX IF NOT EXISTS idx_recoup_app_principals_capabilities ON recoup_app_principals USING gin (capabilities);

REVOKE ALL ON TABLE recoup_memory_records FROM anon, authenticated;
REVOKE ALL ON TABLE recoup_app_principals FROM anon, authenticated;
REVOKE ALL ON TABLE recoup_config FROM anon, authenticated, service_role;
REVOKE ALL ON TABLE recoup_audit_chain FROM anon, authenticated, service_role;
REVOKE ALL ON TABLE recoup_src_bureau FROM anon, authenticated, service_role;
REVOKE ALL ON TABLE recoup_src_docs FROM anon, authenticated, service_role;
REVOKE ALL ON TABLE recoup_src_remittance FROM anon, authenticated, service_role;
REVOKE ALL ON TABLE recoup_src_tpm FROM anon, authenticated, service_role;
GRANT SELECT, INSERT, UPDATE ON TABLE recoup_memory_records TO service_role;
GRANT SELECT, INSERT, UPDATE ON TABLE recoup_app_principals TO service_role;
GRANT SELECT, INSERT ON TABLE recoup_config TO service_role;
GRANT SELECT, INSERT ON TABLE recoup_audit_chain TO service_role;
GRANT SELECT ON TABLE recoup_src_bureau TO service_role;
GRANT SELECT ON TABLE recoup_src_docs TO service_role;
GRANT SELECT ON TABLE recoup_src_remittance TO service_role;
GRANT SELECT ON TABLE recoup_src_tpm TO service_role;

INSERT INTO recoup_app_principals (principal, capabilities)
VALUES ('human:owner-ratified-day-1', ARRAY['config:approve'])
ON CONFLICT (principal) DO NOTHING;

INSERT INTO recoup_config (config_version, key, value_json, config_hash, effective_from, approved_by, active)
VALUES
  (1, 'arbitration_weights', '{"billing":0.15,"collections":0.25,"credit":0.35,"fulfillment":0.25}'::jsonb, '56f3e25e4bf142d892dfb62fa95f6381b06cc2a37c683ebf753e35dab33882d3', '2026-06-20T00:00:00.000Z', 'human:owner-ratified-day-1', true),
  (1, 'r_score_weights', '{"agingConcentration":0.2,"disputeRate":0.25,"dsoAdp":0.35,"overLimitFrequency":0.2}'::jsonb, '4ea963eaba50a3e2584c98fe645111cdf11691c94b30101bcab679a5a97ab583', '2026-06-20T00:00:00.000Z', 'human:owner-ratified-day-1', true),
  (1, 'r_drift', '{"cooldownDays":30,"disputeRateRelativeIncrease":0.5,"dsoIncreaseDays":10,"riskTierDowngrade":1}'::jsonb, '20737251ea98b1954a65bef7597cfa917e3d214f4b928ac84ff37e5a770d1229', '2026-06-20T00:00:00.000Z', 'human:owner-ratified-day-1', true),
  (1, 'gaming_gate', '{"invalidLineCount":2,"invalidValueFloor":"10000.00","promoCorrelationCount":1,"windowDays":90}'::jsonb, 'c43c067c1e93d370b6532037aa457fe7657bc32ee2902184070ec9732f4832da', '2026-06-20T00:00:00.000Z', 'human:owner-ratified-day-1', true),
  (1, 'partial_hold', '{"thresholds":{"holdBelow":40,"maxPartialReleasePercent":70,"minPartialReleasePercent":40,"partialFrom":40,"partialThrough":60,"releaseStepPercent":5,"shipAbove":60},"weights":{"customerStrategicValue":0.15,"dsoPaymentDrift":0.2,"orderMargin":0.15,"orderValueVsExposure":0.2,"paymentPattern":0.15,"revenueForecast":0.15}}'::jsonb, '28be0db356b04a2f8bf212bf1aeac18e684807acaf4b3ac59b4e11007d1c55b4', '2026-06-20T00:00:00.000Z', 'human:owner-ratified-day-1', true),
  (1, 'accuracy_bars', '{"arbitrationAgreement":0.85,"deductionValidityAccuracy":0.9,"intentPrecision":0.9}'::jsonb, '18b1200e6d1ebfc52da2d0dd483c3a79643fd3a04a8f9a3268754603efa920ad', '2026-06-20T00:00:00.000Z', 'human:owner-ratified-day-1', true),
  (1, 'seed', '{"seed":42}'::jsonb, '2a6d2033c7eb061d437f93d7fabf0ec70b6fb4e2edba2e9878fbf59e80bc9862', '2026-06-20T00:00:00.000Z', 'human:owner-ratified-day-1', true)
ON CONFLICT (config_version, key) DO NOTHING;

ALTER TABLE recoup_app_principals ENABLE ROW LEVEL SECURITY;
ALTER TABLE recoup_app_principals FORCE ROW LEVEL SECURITY;
ALTER TABLE recoup_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE recoup_config FORCE ROW LEVEL SECURITY;
ALTER TABLE recoup_audit_chain ENABLE ROW LEVEL SECURITY;
ALTER TABLE recoup_audit_chain FORCE ROW LEVEL SECURITY;
ALTER TABLE recoup_src_bureau ENABLE ROW LEVEL SECURITY;
ALTER TABLE recoup_src_bureau FORCE ROW LEVEL SECURITY;
ALTER TABLE recoup_src_docs ENABLE ROW LEVEL SECURITY;
ALTER TABLE recoup_src_docs FORCE ROW LEVEL SECURITY;
ALTER TABLE recoup_src_remittance ENABLE ROW LEVEL SECURITY;
ALTER TABLE recoup_src_remittance FORCE ROW LEVEL SECURITY;
ALTER TABLE recoup_src_tpm ENABLE ROW LEVEL SECURITY;
ALTER TABLE recoup_src_tpm FORCE ROW LEVEL SECURITY;
ALTER TABLE recoup_memory_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE recoup_memory_records FORCE ROW LEVEL SECURITY;
