CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS recoup_app_principals (
  principal text PRIMARY KEY,
  capabilities text[] NOT NULL DEFAULT ARRAY[]::text[],
  created_at timestamptz NOT NULL DEFAULT now()
);

DROP INDEX IF EXISTS idx_recoup_config_active_key;

CREATE TABLE IF NOT EXISTS recoup_config (
  config_version int NOT NULL,
  key text NOT NULL CHECK (key IN ('arbitration_weights', 'r_score_weights', 'r_drift', 'gaming_gate', 'partial_hold', 'accuracy_bars', 'risk_mesh_cases', 'seed', 'run_control', 'release_eval_label_manifest', 'intent_eval_labels', 'arbitration_eval_labels', 'decision_confidence_threshold')),
  value_json jsonb NOT NULL CHECK (jsonb_typeof(value_json) = 'object'),
  config_hash text NOT NULL CHECK (config_hash ~ '^[a-f0-9]{64}$'),
  effective_from timestamptz NOT NULL,
  approved_by text NOT NULL REFERENCES recoup_app_principals(principal),
  active boolean NOT NULL DEFAULT true,
  PRIMARY KEY (config_version, key)
);

CREATE TABLE IF NOT EXISTS recoup_audit_chain (
  entry_hash text PRIMARY KEY CHECK (entry_hash ~ '^[a-f0-9]{64}$'),
  prev_hash text CHECK (prev_hash IS NULL OR prev_hash ~ '^[a-f0-9]{64}$'),
  payload jsonb NOT NULL CHECK (jsonb_typeof(payload) = 'object'),
  seq bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS recoup_customers (
  customer_id text PRIMARY KEY,
  name text NOT NULL,
  profile text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS recoup_deduction_lines (
  line_id text PRIMARY KEY,
  scenario_id text NOT NULL CHECK (scenario_id IN ('S1', 'S2', 'S3', 'S4', 'S5', 'S6', 'S7', 'S8')),
  customer_id text NOT NULL REFERENCES recoup_customers(customer_id),
  scenario_type text NOT NULL,
  amount numeric NOT NULL,
  verdict text NOT NULL CHECK (verdict IN ('valid', 'invalid', 'partial')),
  routing text NOT NULL CHECK (routing IN ('billing', 'recovery')),
  record_ids_json jsonb NOT NULL CHECK (jsonb_typeof(record_ids_json) = 'array' AND jsonb_array_length(record_ids_json) > 0),
  rule_id text NOT NULL,
  rule_input_json jsonb NOT NULL CHECK (jsonb_typeof(rule_input_json) = 'object'),
  period text NOT NULL,
  event_id text NOT NULL CHECK (event_id ~ '^[a-f0-9]{64}$'),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS recoup_src_bureau (
  customer_id text NOT NULL,
  bureau_id text PRIMARY KEY,
  as_of_date date NOT NULL,
  risk_score int NOT NULL CHECK (risk_score >= 0 AND risk_score <= 100),
  limit_recommendation numeric NOT NULL,
  public_records jsonb NOT NULL CHECK (jsonb_typeof(public_records) = 'object'),
  delinquency_flag boolean NOT NULL,
  provenance text NOT NULL CHECK (provenance = 'synthetic')
);

CREATE TABLE IF NOT EXISTS recoup_src_docs (
  doc_id text PRIMARY KEY,
  doc_type text NOT NULL CHECK (doc_type IN ('POD', 'contract', 'TPM', 'correspondence')),
  customer_id text NOT NULL,
  linked_record_ids jsonb NOT NULL CHECK (jsonb_typeof(linked_record_ids) = 'array' AND jsonb_array_length(linked_record_ids) > 0),
  uri text NOT NULL,
  signed_date date,
  provenance text NOT NULL CHECK (provenance = 'synthetic')
);

CREATE TABLE IF NOT EXISTS recoup_src_remittance (
  remit_id text PRIMARY KEY,
  transaction_set text NOT NULL CHECK (transaction_set IN ('820', '812', '810', 'manual')),
  customer_id text NOT NULL,
  paid_amount numeric NOT NULL,
  invoice_refs jsonb NOT NULL CHECK (jsonb_typeof(invoice_refs) = 'array'),
  deduction_refs jsonb NOT NULL CHECK (jsonb_typeof(deduction_refs) = 'array'),
  payment_date date NOT NULL,
  currency text NOT NULL,
  provenance text NOT NULL CHECK (provenance = 'synthetic')
);

CREATE TABLE IF NOT EXISTS recoup_src_sap (
  sap_document_id text PRIMARY KEY,
  document_type text NOT NULL CHECK (document_type IN ('invoice', 'credit-memo')),
  customer_id text NOT NULL,
  service_name text NOT NULL,
  entity_set text NOT NULL,
  linked_record_ids jsonb NOT NULL CHECK (jsonb_typeof(linked_record_ids) = 'array' AND jsonb_array_length(linked_record_ids) > 0),
  payload_json jsonb NOT NULL CHECK (jsonb_typeof(payload_json) = 'object'),
  summary text NOT NULL,
  retrieved_at timestamptz NOT NULL,
  provenance text NOT NULL CHECK (provenance = 'sap-odata')
);

CREATE TABLE IF NOT EXISTS recoup_src_tpm (
  promo_id text PRIMARY KEY,
  customer_id text NOT NULL,
  product_scope jsonb NOT NULL CHECK (jsonb_typeof(product_scope) = 'object'),
  promo_type text NOT NULL,
  approved_allowance numeric NOT NULL,
  accrued_amount numeric NOT NULL,
  window_start date NOT NULL,
  window_end date NOT NULL,
  claim_refs jsonb NOT NULL CHECK (jsonb_typeof(claim_refs) = 'array'),
  provenance text NOT NULL CHECK (provenance = 'synthetic'),
  CHECK (window_end >= window_start)
);

CREATE TABLE IF NOT EXISTS recoup_source_health_snapshots (
  source_name text PRIMARY KEY,
  status text NOT NULL CHECK (status IN ('connected', 'degraded', 'blocked')),
  source_mode text NOT NULL CHECK (source_mode IN ('live', 'synthetic_static_table', 'unavailable')),
  checked_at timestamptz NOT NULL,
  latency_ms int NOT NULL CHECK (latency_ms >= 0),
  proof_items_json jsonb NOT NULL CHECK (jsonb_typeof(proof_items_json) = 'array' AND jsonb_array_length(proof_items_json) > 0),
  record_ids_json jsonb NOT NULL CHECK (jsonb_typeof(record_ids_json) = 'array' AND jsonb_array_length(record_ids_json) > 0),
  last_error text,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS customers (
  customer_id text PRIMARY KEY,
  customer_name text NOT NULL,
  segment text,
  strategic_value text,
  credit_limit numeric NOT NULL DEFAULT 0,
  revenue_forecast_12mo numeric NOT NULL DEFAULT 0,
  r_score_component_scores_json jsonb CHECK (
    r_score_component_scores_json IS NULL OR (
      jsonb_typeof(r_score_component_scores_json) = 'object'
      AND r_score_component_scores_json ?& ARRAY['agingConcentration', 'disputeRate', 'dsoAdp', 'overLimitFrequency']
      AND jsonb_typeof(r_score_component_scores_json->'agingConcentration') = 'number'
      AND jsonb_typeof(r_score_component_scores_json->'disputeRate') = 'number'
      AND jsonb_typeof(r_score_component_scores_json->'dsoAdp') = 'number'
      AND jsonb_typeof(r_score_component_scores_json->'overLimitFrequency') = 'number'
      AND (r_score_component_scores_json->>'agingConcentration')::numeric BETWEEN 0 AND 100
      AND (r_score_component_scores_json->>'disputeRate')::numeric BETWEEN 0 AND 100
      AND (r_score_component_scores_json->>'dsoAdp')::numeric BETWEEN 0 AND 100
      AND (r_score_component_scores_json->>'overLimitFrequency')::numeric BETWEEN 0 AND 100
    )
  ),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS payments (
  payment_id text PRIMARY KEY DEFAULT gen_random_uuid()::text,
  customer_id text NOT NULL,
  invoice_ref text NOT NULL,
  invoice_amount numeric NOT NULL,
  invoice_date date NOT NULL,
  payment_date date NOT NULL,
  days_to_pay int NOT NULL CHECK (days_to_pay >= 0),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS pod_records (
  pod_id text PRIMARY KEY DEFAULT gen_random_uuid()::text,
  sales_order_ref text NOT NULL,
  delivery_ref text NOT NULL,
  invoice_ref text NOT NULL,
  customer_id text NOT NULL,
  carrier_name text,
  delivery_timestamp timestamptz,
  target_delivery_date date,
  shipped_qty int NOT NULL CHECK (shipped_qty >= 0),
  signed_qty int NOT NULL CHECK (signed_qty >= 0),
  discrepancy_note text,
  signed_by text,
  signature_image_url text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS promotions (
  promo_id text PRIMARY KEY,
  customer_id text NOT NULL,
  sku text NOT NULL,
  promo_rate numeric NOT NULL,
  accrual_cap numeric NOT NULL DEFAULT 0,
  start_date date NOT NULL,
  end_date date NOT NULL,
  promo_description text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (end_date >= start_date)
);

CREATE TABLE IF NOT EXISTS contracts (
  contract_id text PRIMARY KEY,
  customer_id text NOT NULL,
  pricing_model text,
  otif_threshold numeric NOT NULL DEFAULT 98,
  fine_percentage numeric NOT NULL DEFAULT 0,
  pricing_terms jsonb CHECK (pricing_terms IS NULL OR jsonb_typeof(pricing_terms) = 'object'),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS carrier_reports (
  report_id text PRIMARY KEY DEFAULT gen_random_uuid()::text,
  invoice_ref text NOT NULL,
  customer_id text NOT NULL,
  carrier_name text,
  damage_description text,
  damaged_qty int NOT NULL CHECK (damaged_qty >= 0),
  report_status text NOT NULL DEFAULT 'SUBMITTED' CHECK (report_status IN ('SUBMITTED', 'VERIFIED', 'REJECTED')),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS damage_photos (
  photo_id text PRIMARY KEY DEFAULT gen_random_uuid()::text,
  report_id text,
  photo_url text NOT NULL,
  uploaded_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS bureau_alerts (
  alert_id text PRIMARY KEY DEFAULT gen_random_uuid()::text,
  customer_id text NOT NULL,
  alert_type text NOT NULL,
  severity text NOT NULL,
  details text,
  alert_date date NOT NULL,
  resolved boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS remittance_headers (
  remittance_id text PRIMARY KEY DEFAULT gen_random_uuid()::text,
  customer_id text NOT NULL,
  remittance_date date NOT NULL,
  payment_reference text,
  total_amount_paid numeric NOT NULL,
  total_deductions numeric NOT NULL DEFAULT 0,
  ocr_confidence numeric,
  pdf_url text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS remittance_lines (
  line_id text PRIMARY KEY DEFAULT gen_random_uuid()::text,
  remittance_id text,
  invoice_ref text NOT NULL,
  deducted_amount numeric NOT NULL,
  reason_code_raw text,
  reason_code_mapped text,
  disputed_sku text,
  disputed_qty int CHECK (disputed_qty IS NULL OR disputed_qty >= 0),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS deductions_backlog (
  deduction_id text PRIMARY KEY DEFAULT gen_random_uuid()::text,
  line_ref text,
  customer_id text NOT NULL,
  invoice_ref text NOT NULL,
  amount numeric NOT NULL DEFAULT 0,
  scenario_type text NOT NULL,
  verdict text NOT NULL CHECK (verdict IN ('PENDING', 'VALID', 'INVALID', 'PARTIAL')),
  confidence numeric NOT NULL DEFAULT 0,
  explanation text,
  assigned_analyst text,
  status text NOT NULL DEFAULT 'OPEN',
  gaming_pattern_flag boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS billing_requests (
  request_id text PRIMARY KEY DEFAULT gen_random_uuid()::text,
  deduction_id text,
  invoice_ref text NOT NULL,
  type text NOT NULL CHECK (type IN ('CREDIT_MEMO', 'CREDIT_AND_REBILL', 'WRITE_OFF')),
  amount numeric NOT NULL,
  gl_code text,
  re_bill_amount numeric NOT NULL DEFAULT 0,
  re_bill_unit_price numeric NOT NULL DEFAULT 0,
  supporting_evidence_urls text[] NOT NULL DEFAULT ARRAY[]::text[],
  status text NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT', 'APPROVED', 'SENT_TO_SAP', 'CONFIRMED')),
  audit_id text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS recovery_packages (
  package_id text PRIMARY KEY DEFAULT gen_random_uuid()::text,
  deduction_id text,
  customer_id text NOT NULL,
  invoice_ref text NOT NULL,
  amount numeric NOT NULL,
  correspondence_letter text,
  evidence_package_json jsonb CHECK (evidence_package_json IS NULL OR jsonb_typeof(evidence_package_json) = 'object'),
  status text NOT NULL DEFAULT 'GENERATED' CHECK (status IN ('GENERATED', 'SUBMITTED_TO_PORTAL', 'PAID', 'ABANDONED')),
  follow_up_cadence_count int NOT NULL DEFAULT 0 CHECK (follow_up_cadence_count >= 0),
  next_follow_up_date date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS credit_decisions (
  decision_id text PRIMARY KEY DEFAULT gen_random_uuid()::text,
  customer_id text NOT NULL,
  blocked_order_ref text NOT NULL,
  order_amount numeric NOT NULL,
  credit_limit_amount numeric NOT NULL,
  dso_drift_days int NOT NULL,
  margin_percentage numeric NOT NULL,
  customer_strategic_segment text NOT NULL,
  composite_release_score numeric NOT NULL,
  release_ratio numeric NOT NULL,
  released_amount numeric NOT NULL,
  held_amount numeric NOT NULL,
  proposed_terms text,
  decision_verdict text NOT NULL DEFAULT 'PROPOSED' CHECK (decision_verdict IN ('PROPOSED', 'APPROVED', 'OVERRIDDEN', 'REJECTED')),
  arbitrator_user text,
  negotiation_log jsonb CHECK (negotiation_log IS NULL OR jsonb_typeof(negotiation_log) = 'object'),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS immutable_audit_log (
  audit_id text PRIMARY KEY DEFAULT gen_random_uuid()::text,
  action_type text NOT NULL,
  ref_id text NOT NULL,
  payload jsonb NOT NULL CHECK (jsonb_typeof(payload) = 'object'),
  operator_user text NOT NULL,
  recorded_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS recoup_memory_records (
  sequence bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id text NOT NULL,
  category text NOT NULL CHECK (category IN ('session_state', 'workflow_state', 'case_state', 'transaction_state', 'evidence_refs', 'approval_records', 'audit_refs', 'connector_state', 'compaction_summaries', 'artifact_refs', 'agent_handoff_packets')),
  trust_level text NOT NULL CHECK (trust_level IN ('trusted', 'semi_trusted', 'untrusted')),
  scope text NOT NULL,
  payload_json jsonb NOT NULL CHECK (jsonb_typeof(payload_json) = 'object'),
  record_ids_json jsonb NOT NULL CHECK (jsonb_typeof(record_ids_json) = 'array' AND jsonb_array_length(record_ids_json) > 0),
  created_at timestamptz NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_recoup_config_version ON recoup_config (config_version);
CREATE UNIQUE INDEX IF NOT EXISTS idx_recoup_audit_chain_seq ON recoup_audit_chain (seq);
CREATE INDEX IF NOT EXISTS idx_recoup_deduction_lines_customer_scenario ON recoup_deduction_lines (customer_id, scenario_id);
CREATE INDEX IF NOT EXISTS idx_recoup_deduction_lines_record_ids ON recoup_deduction_lines USING gin (record_ids_json);
CREATE INDEX IF NOT EXISTS idx_recoup_src_bureau_customer_date ON recoup_src_bureau (customer_id, as_of_date);
CREATE INDEX IF NOT EXISTS idx_recoup_src_docs_customer ON recoup_src_docs (customer_id);
CREATE INDEX IF NOT EXISTS idx_recoup_src_docs_linked_record_ids ON recoup_src_docs USING gin (linked_record_ids);
CREATE INDEX IF NOT EXISTS idx_recoup_src_remittance_customer_payment ON recoup_src_remittance (customer_id, payment_date);
CREATE INDEX IF NOT EXISTS idx_recoup_src_remittance_invoice_refs ON recoup_src_remittance USING gin (invoice_refs);
CREATE INDEX IF NOT EXISTS idx_recoup_src_remittance_deduction_refs ON recoup_src_remittance USING gin (deduction_refs);
CREATE INDEX IF NOT EXISTS idx_recoup_src_sap_customer ON recoup_src_sap (customer_id);
CREATE INDEX IF NOT EXISTS idx_recoup_src_sap_linked_record_ids ON recoup_src_sap USING gin (linked_record_ids);
CREATE INDEX IF NOT EXISTS idx_recoup_src_tpm_customer_window ON recoup_src_tpm (customer_id, window_start, window_end);
CREATE INDEX IF NOT EXISTS idx_recoup_src_tpm_claim_refs ON recoup_src_tpm USING gin (claim_refs);
CREATE INDEX IF NOT EXISTS idx_payments_customer_invoice_ref ON payments (customer_id, invoice_ref);
CREATE INDEX IF NOT EXISTS idx_pod_records_invoice ON pod_records (invoice_ref);
CREATE INDEX IF NOT EXISTS idx_pod_records_delivery ON pod_records (delivery_ref);
CREATE INDEX IF NOT EXISTS idx_promotions_customer_window ON promotions (customer_id, start_date, end_date);
CREATE INDEX IF NOT EXISTS idx_contracts_customer ON contracts (customer_id);
CREATE INDEX IF NOT EXISTS idx_carrier_reports_customer_invoice ON carrier_reports (customer_id, invoice_ref);
CREATE INDEX IF NOT EXISTS idx_damage_photos_report ON damage_photos (report_id);
CREATE INDEX IF NOT EXISTS idx_bureau_alerts_customer_type ON bureau_alerts (customer_id, alert_type, severity, resolved);
CREATE INDEX IF NOT EXISTS idx_remittance_headers_customer_date ON remittance_headers (customer_id, remittance_date);
CREATE INDEX IF NOT EXISTS idx_remittance_lines_invoice_ref ON remittance_lines (invoice_ref);
CREATE INDEX IF NOT EXISTS idx_deductions_backlog_customer_verdict ON deductions_backlog (customer_id, verdict);
CREATE INDEX IF NOT EXISTS idx_billing_requests_status ON billing_requests (status);
CREATE INDEX IF NOT EXISTS idx_recovery_packages_status ON recovery_packages (status);
CREATE INDEX IF NOT EXISTS idx_credit_decisions_customer_order ON credit_decisions (customer_id, blocked_order_ref);
CREATE INDEX IF NOT EXISTS idx_immutable_audit_log_ref ON immutable_audit_log (ref_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_recoup_memory_records_id ON recoup_memory_records (id);
CREATE INDEX IF NOT EXISTS idx_recoup_memory_records_scope_sequence ON recoup_memory_records (scope, sequence);
CREATE INDEX IF NOT EXISTS idx_recoup_memory_records_record_ids ON recoup_memory_records USING gin (record_ids_json);
CREATE INDEX IF NOT EXISTS idx_recoup_app_principals_capabilities ON recoup_app_principals USING gin (capabilities);

CREATE OR REPLACE FUNCTION recoup_commit_approval_audit(
  p_expected_prev_hash text,
  p_audit_entry_hash text,
  p_audit_prev_hash text,
  p_audit_payload jsonb,
  p_memory_table_name text,
  p_memory_id text,
  p_memory_category text,
  p_memory_trust_level text,
  p_memory_scope text,
  p_memory_payload_json jsonb,
  p_memory_record_ids_json jsonb,
  p_memory_created_at timestamptz
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  current_tail_hash text;
BEGIN
  IF p_memory_table_name <> 'recoup_memory_records' THEN
    RAISE EXCEPTION 'unsafe_memory_table_name';
  END IF;

  LOCK TABLE recoup_audit_chain IN EXCLUSIVE MODE;

  SELECT entry_hash
  INTO current_tail_hash
  FROM recoup_audit_chain
  ORDER BY seq DESC
  LIMIT 1;

  IF NOT (p_expected_prev_hash IS NOT DISTINCT FROM current_tail_hash) THEN
    RAISE EXCEPTION 'audit_tail_mismatch';
  END IF;

  IF p_audit_prev_hash IS DISTINCT FROM current_tail_hash THEN
    RAISE EXCEPTION 'audit_tail_mismatch';
  END IF;

  INSERT INTO recoup_audit_chain (entry_hash, prev_hash, payload)
  VALUES (p_audit_entry_hash, p_audit_prev_hash, p_audit_payload);

  EXECUTE format(
    'INSERT INTO %I (id, category, trust_level, scope, payload_json, record_ids_json, created_at) VALUES ($1, $2, $3, $4, $5, $6, $7)',
    p_memory_table_name
  )
  USING
    p_memory_id,
    p_memory_category,
    p_memory_trust_level,
    p_memory_scope,
    p_memory_payload_json,
    p_memory_record_ids_json,
    p_memory_created_at;
END;
$$;

REVOKE ALL ON TABLE recoup_memory_records FROM anon, authenticated;
REVOKE ALL ON TABLE recoup_app_principals FROM anon, authenticated;
REVOKE ALL ON TABLE recoup_config FROM anon, authenticated, service_role;
REVOKE ALL ON TABLE recoup_audit_chain FROM anon, authenticated, service_role;
REVOKE ALL ON TABLE recoup_customers FROM anon, authenticated, service_role;
REVOKE ALL ON TABLE recoup_deduction_lines FROM anon, authenticated, service_role;
REVOKE ALL ON TABLE recoup_src_bureau FROM anon, authenticated, service_role;
REVOKE ALL ON TABLE recoup_src_docs FROM anon, authenticated, service_role;
REVOKE ALL ON TABLE recoup_src_remittance FROM anon, authenticated, service_role;
REVOKE ALL ON TABLE recoup_src_sap FROM anon, authenticated, service_role;
REVOKE ALL ON TABLE recoup_src_tpm FROM anon, authenticated, service_role;
REVOKE ALL ON TABLE recoup_source_health_snapshots FROM anon, authenticated, service_role;
REVOKE ALL ON TABLE customers FROM anon, authenticated, service_role;
REVOKE ALL ON TABLE payments FROM anon, authenticated, service_role;
REVOKE ALL ON TABLE pod_records FROM anon, authenticated, service_role;
REVOKE ALL ON TABLE promotions FROM anon, authenticated, service_role;
REVOKE ALL ON TABLE contracts FROM anon, authenticated, service_role;
REVOKE ALL ON TABLE carrier_reports FROM anon, authenticated, service_role;
REVOKE ALL ON TABLE damage_photos FROM anon, authenticated, service_role;
REVOKE ALL ON TABLE bureau_alerts FROM anon, authenticated, service_role;
REVOKE ALL ON TABLE remittance_headers FROM anon, authenticated, service_role;
REVOKE ALL ON TABLE remittance_lines FROM anon, authenticated, service_role;
REVOKE ALL ON TABLE deductions_backlog FROM anon, authenticated, service_role;
REVOKE ALL ON TABLE billing_requests FROM anon, authenticated, service_role;
REVOKE ALL ON TABLE recovery_packages FROM anon, authenticated, service_role;
REVOKE ALL ON TABLE credit_decisions FROM anon, authenticated, service_role;
REVOKE ALL ON TABLE immutable_audit_log FROM anon, authenticated, service_role;
REVOKE ALL ON FUNCTION recoup_commit_approval_audit(text, text, text, jsonb, text, text, text, text, text, jsonb, jsonb, timestamptz) FROM PUBLIC, anon, authenticated, service_role;
GRANT SELECT, INSERT, UPDATE ON TABLE recoup_memory_records TO service_role;
GRANT SELECT, INSERT, UPDATE ON TABLE recoup_app_principals TO service_role;
GRANT SELECT, INSERT ON TABLE recoup_config TO service_role;
GRANT SELECT ON TABLE recoup_audit_chain TO service_role;
GRANT EXECUTE ON FUNCTION recoup_commit_approval_audit(text, text, text, jsonb, text, text, text, text, text, jsonb, jsonb, timestamptz) TO service_role;
GRANT SELECT ON TABLE recoup_customers TO service_role;
GRANT SELECT ON TABLE recoup_deduction_lines TO service_role;
GRANT SELECT ON TABLE recoup_src_bureau TO service_role;
GRANT SELECT ON TABLE recoup_src_docs TO service_role;
GRANT SELECT ON TABLE recoup_src_remittance TO service_role;
GRANT SELECT ON TABLE recoup_src_sap TO service_role;
GRANT SELECT ON TABLE recoup_src_tpm TO service_role;
GRANT SELECT, INSERT, UPDATE ON TABLE recoup_source_health_snapshots TO service_role;
GRANT SELECT ON TABLE customers TO service_role;
GRANT SELECT ON TABLE payments TO service_role;
GRANT SELECT ON TABLE pod_records TO service_role;
GRANT SELECT ON TABLE promotions TO service_role;
GRANT SELECT ON TABLE contracts TO service_role;
GRANT SELECT ON TABLE carrier_reports TO service_role;
GRANT SELECT ON TABLE damage_photos TO service_role;
GRANT SELECT ON TABLE bureau_alerts TO service_role;
GRANT SELECT ON TABLE remittance_headers TO service_role;
GRANT SELECT ON TABLE remittance_lines TO service_role;
GRANT SELECT ON TABLE deductions_backlog TO service_role;
GRANT SELECT ON TABLE billing_requests TO service_role;
GRANT SELECT ON TABLE recovery_packages TO service_role;
GRANT SELECT ON TABLE credit_decisions TO service_role;
GRANT SELECT ON TABLE immutable_audit_log TO service_role;

INSERT INTO recoup_app_principals (principal, capabilities)
VALUES
  ('human:owner-ratified-day-1', ARRAY['config:approve']),
  ('human:rathish-owner', ARRAY['config:approve', 'release:approve'])
ON CONFLICT (principal) DO NOTHING;

INSERT INTO recoup_config (config_version, key, value_json, config_hash, effective_from, approved_by, active)
VALUES
  (1, 'arbitration_weights', '{"billing":0.15,"collections":0.2,"credit":0.35,"fulfillment":0.3}'::jsonb, '00ef51f5b38a5e6f28f09e1f05ba44517629e43d1d1584cdfc26472f3dbd21f2', '2026-06-20T00:00:00.000Z', 'human:owner-ratified-day-1', true),
  (1, 'r_score_weights', '{"agingConcentration":0.2,"disputeRate":0.25,"dsoAdp":0.35,"overLimitFrequency":0.2}'::jsonb, '4ea963eaba50a3e2584c98fe645111cdf11691c94b30101bcab679a5a97ab583', '2026-06-20T00:00:00.000Z', 'human:owner-ratified-day-1', true),
  (1, 'r_drift', '{"cooldownDays":30,"disputeRateRelativeIncrease":0.5,"dsoIncreaseDays":10,"riskTierDowngrade":1}'::jsonb, '20737251ea98b1954a65bef7597cfa917e3d214f4b928ac84ff37e5a770d1229', '2026-06-20T00:00:00.000Z', 'human:owner-ratified-day-1', true),
  (1, 'gaming_gate', '{"invalidLineCount":2,"invalidValueFloor":"10000.00","promoCorrelationCount":1,"windowDays":90}'::jsonb, 'c43c067c1e93d370b6532037aa457fe7657bc32ee2902184070ec9732f4832da', '2026-06-20T00:00:00.000Z', 'human:owner-ratified-day-1', true),
  (1, 'partial_hold', '{"thresholds":{"holdBelow":40,"maxPartialReleasePercent":70,"minPartialReleasePercent":40,"partialFrom":40,"partialThrough":60,"releaseStepPercent":5,"shipAbove":60},"weights":{"customerStrategicValue":0.15,"dsoPaymentDrift":0.2,"orderMargin":0.15,"orderValueVsExposure":0.2,"paymentPattern":0.15,"revenueForecast":0.15}}'::jsonb, '28be0db356b04a2f8bf212bf1aeac18e684807acaf4b3ac59b4e11007d1c55b4', '2026-06-20T00:00:00.000Z', 'human:owner-ratified-day-1', true),
  (1, 'accuracy_bars', '{"arbitrationAgreement":0.85,"deductionValidityAccuracy":0.9,"intentPrecision":0.9}'::jsonb, '18b1200e6d1ebfc52da2d0dd483c3a79643fd3a04a8f9a3268754603efa920ad', '2026-06-20T00:00:00.000Z', 'human:owner-ratified-day-1', true),
  (1, 'risk_mesh_cases', '{"harbor":{"accountReadout":{"availableCreditLabel":"Pending ERP","creditProgram":"Global standard","hqRegion":"Houston, TX / NA","industry":"Maritime services","legalEntity":"Harbor Holdings LLC","limitLabel":"Pending ERP","openArLabel":"Pending ERP","ownerLabel":"David Kim","posture":"Human approval required"},"actionQueue":[{"account":"Harbor","age":"00h 42m","item":"Bureau lien alert","nextStep":"Review lien","priority":"P1","status":"New"},{"account":"Harbor","age":"01h 15m","item":"Partial-hold recommended","nextStep":"Review & send","priority":"P1","status":"Action required"},{"account":"Harbor","age":"02h 10m","item":"DSO drift alert","nextStep":"View DSO","priority":"P2","status":"Investigate"},{"account":"Harbor","age":"04h 02m","item":"Order exposure update","nextStep":"Review exposure","priority":"P3","status":"Advisory"},{"account":"Harbor","age":"06h 33m","item":"Policy exception","nextStep":"Review exception","priority":"P3","status":"Advisory"}],"arbitrationPositions":[{"functionName":"credit","optionId":"partial_release_55","optionValue":"0.80","position":"Partial release 55% + revised terms: owner-supplied credit-risk / loss avoidance option value.","recordIds":["CUST-HARBOR","USCU_S04","6534","LEDGER-6-PARTIAL-HOLD"]},{"functionName":"fulfillment","optionId":"partial_release_55","optionValue":"0.65","position":"Partial release 55% + revised terms: owner-supplied revenue / fulfilment option value.","recordIds":["CUST-HARBOR","USCU_S04","6534","LEDGER-6-PARTIAL-HOLD"]},{"functionName":"collections","optionId":"partial_release_55","optionValue":"0.85","position":"Partial release 55% + revised terms: owner-supplied collections recoverability option value.","recordIds":["CUST-HARBOR","USCU_S04","6534","LEDGER-6-PARTIAL-HOLD"]},{"functionName":"billing","optionId":"partial_release_55","optionValue":"0.75","position":"Partial release 55% + revised terms: owner-supplied relationship / strategic continuity option value.","recordIds":["CUST-HARBOR","USCU_S04","6534","LEDGER-6-PARTIAL-HOLD"]},{"functionName":"credit","optionId":"full_release_revised_terms","optionValue":"0.35","position":"Full release on revised terms: owner-supplied credit-risk / loss avoidance option value.","recordIds":["CUST-HARBOR","USCU_S04","6534","LEDGER-6-PARTIAL-HOLD"]},{"functionName":"fulfillment","optionId":"full_release_revised_terms","optionValue":"0.90","position":"Full release on revised terms: owner-supplied revenue / fulfilment option value.","recordIds":["CUST-HARBOR","USCU_S04","6534","LEDGER-6-PARTIAL-HOLD"]},{"functionName":"collections","optionId":"full_release_revised_terms","optionValue":"0.70","position":"Full release on revised terms: owner-supplied collections recoverability option value.","recordIds":["CUST-HARBOR","USCU_S04","6534","LEDGER-6-PARTIAL-HOLD"]},{"functionName":"billing","optionId":"full_release_revised_terms","optionValue":"0.85","position":"Full release on revised terms: owner-supplied relationship / strategic continuity option value.","recordIds":["CUST-HARBOR","USCU_S04","6534","LEDGER-6-PARTIAL-HOLD"]},{"functionName":"credit","optionId":"full_release_100","optionValue":"0.20","position":"Full release 100% current terms: owner-supplied credit-risk / loss avoidance option value.","recordIds":["CUST-HARBOR","USCU_S04","6534","LEDGER-6-PARTIAL-HOLD"]},{"functionName":"fulfillment","optionId":"full_release_100","optionValue":"0.95","position":"Full release 100% current terms: owner-supplied revenue / fulfilment option value.","recordIds":["CUST-HARBOR","USCU_S04","6534","LEDGER-6-PARTIAL-HOLD"]},{"functionName":"collections","optionId":"full_release_100","optionValue":"0.30","position":"Full release 100% current terms: owner-supplied collections recoverability option value.","recordIds":["CUST-HARBOR","USCU_S04","6534","LEDGER-6-PARTIAL-HOLD"]},{"functionName":"billing","optionId":"full_release_100","optionValue":"0.90","position":"Full release 100% current terms: owner-supplied relationship / strategic continuity option value.","recordIds":["CUST-HARBOR","USCU_S04","6534","LEDGER-6-PARTIAL-HOLD"]},{"functionName":"credit","optionId":"full_hold_0","optionValue":"0.95","position":"Full hold 0% release: owner-supplied credit-risk / loss avoidance option value.","recordIds":["CUST-HARBOR","USCU_S04","6534","LEDGER-6-PARTIAL-HOLD"]},{"functionName":"fulfillment","optionId":"full_hold_0","optionValue":"0.10","position":"Full hold 0% release: owner-supplied revenue / fulfilment option value.","recordIds":["CUST-HARBOR","USCU_S04","6534","LEDGER-6-PARTIAL-HOLD"]},{"functionName":"collections","optionId":"full_hold_0","optionValue":"0.50","position":"Full hold 0% release: owner-supplied collections recoverability option value.","recordIds":["CUST-HARBOR","USCU_S04","6534","LEDGER-6-PARTIAL-HOLD"]},{"functionName":"billing","optionId":"full_hold_0","optionValue":"0.20","position":"Full hold 0% release: owner-supplied relationship / strategic continuity option value.","recordIds":["CUST-HARBOR","USCU_S04","6534","LEDGER-6-PARTIAL-HOLD"]}],"caseId":"ARB-HARBOR-ORDER-640K","containmentIntentLabel":"distressed-honest","customerId":"CUST-HARBOR","holdBasis":"Harbor worked example computes a 55% controlled release from the deterministic partial-hold core.","orderAmount":"640010.00","orderId":"6534","partialHoldScores":{"customerStrategicValue":60,"dsoPaymentDrift":30,"orderMargin":80,"orderValueVsExposure":35,"paymentPattern":50,"revenueForecast":65},"recordIds":["CUST-HARBOR","USCU_S04","6534","LEDGER-6-PARTIAL-HOLD"],"riskObservationSource":{"baselinePaymentRefs":["90000036","90000060","INV-HARB-003"],"citedDeductionVerdicts":["PARTIAL","INVALID"],"criticalAlertSeverity":"CRITICAL","criticalAlertType":"TAX_LIEN","currentPaymentRef":"90000085","sourceCustomerId":"USCU_S04"},"sentinelDisplay":{"alertDetail":"UCC-1 filing detected and priority review required before any release.","displayReason":"Bureau lien alert","filedLabel":"Filed: pending proof","filingId":"UCC-1-HARBOR-PENDING","recordStripLabel":"Sentinel alert record IDs","securedPartyLabel":"Secured party: proof required"},"terms":"2/10 Net-30 + 25% deposit","termsBasis":"Sentinel drift observation routes revised terms to HITL without self-applying terms."}}'::jsonb, '1e85d61fd4c7faa5614d10bc371eed8a8777dd3d1a40b1b05b1baaab43556863', '2026-06-20T00:00:00.000Z', 'human:owner-ratified-day-1', true),
  (1, 'seed', '{"seed":42}'::jsonb, '2a6d2033c7eb061d437f93d7fabf0ec70b6fb4e2edba2e9878fbf59e80bc9862', '2026-06-20T00:00:00.000Z', 'human:owner-ratified-day-1', true)
ON CONFLICT (config_version, key) DO NOTHING;

INSERT INTO recoup_config (config_version, key, value_json, config_hash, effective_from, approved_by, active)
VALUES
  (1, 'run_control', '{"phases":{"containment":{"retryCap":2,"stepBudget":24,"tokenBudget":45000},"forensics":{"retryCap":2,"stepBudget":80,"tokenBudget":200000},"query":{"retryCap":1,"stepBudget":12,"tokenBudget":32000},"recovery":{"retryCap":2,"stepBudget":40,"tokenBudget":90000},"riskMesh":{"retryCap":2,"stepBudget":36,"tokenBudget":90000},"sentinel":{"retryCap":2,"stepBudget":30,"tokenBudget":70000}}}'::jsonb, '77dfb2833f50f78331984258e15ec5477feb8a330a13db6f5cdc551bb980b6d5', '2026-06-22T00:00:00.000Z', 'human:rathish-owner', true),
  (1, 'release_eval_label_manifest', '{"arbitrationCaseIds":["arb:harbor-order-6534"],"intentCaseIds":["intent:USCU_L10","intent:USCU_S04","intent:USCU_S07","intent:USCU_S03"]}'::jsonb, '66ae8d96a0ece2964fc7283d75212098f120b24b048bcce1f0dc103913663e82', '2026-06-22T00:00:00.000Z', 'human:rathish-owner', true),
  (1, 'intent_eval_labels', '{"labels":[{"actual":"gaming","caseId":"intent:USCU_L10","modelCustomerId":"CUST-CRESTLINE","recordIds":["S3-L1","POD-SIGNED-1","S6-L1","PRICE-CLAUSE-1"],"sapCustomerId":"USCU_L10"},{"actual":"distressed-honest","caseId":"intent:USCU_S04","modelCustomerId":"CUST-HARBOR","recordIds":["FIN-DISP-202","BUREAU-HARBOR-TAX-LIEN","90000036","90000085"],"sapCustomerId":"USCU_S04"},{"actual":"genuine","caseId":"intent:USCU_S07","modelCustomerId":"CUST-VALUMART","recordIds":["S4-L1","SLA-CONTRACT-1","S5-L1","POD-TIMESTAMP-1"],"sapCustomerId":"USCU_S07"},{"actual":"genuine","caseId":"intent:USCU_S03","modelCustomerId":"CUST-GREENLEAF","recordIds":["S1-L1","PHOTO-CARRIER-1","POD-90000002"],"sapCustomerId":"USCU_S03"}]}'::jsonb, 'a0038f6bcb79cade73cb5264c41c28ba1a223063ee67779fbfd196214893efc6', '2026-06-22T00:00:00.000Z', 'human:rathish-owner', true),
  (1, 'arbitration_eval_labels', '{"labels":[{"actual":"partial-release-55|ship=352005.50|backorder=288004.50|terms=2/10 Net-30 + 25% deposit","caseId":"arb:harbor-order-6534","expectedRanking":["partial_release_55","full_release_revised_terms","full_release_100","full_hold_0"],"modelCaseId":"ARB-HARBOR-ORDER-640K","recordIds":["6534","USCU_S04","LEDGER-6-PARTIAL-HOLD"],"sapOrderId":"6534"}]}'::jsonb, '246b86ea6db527a4209956412a8e92bb1726dbc0d7124c6953712e88ede22a0d', '2026-06-22T00:00:00.000Z', 'human:rathish-owner', true),
  (1, 'decision_confidence_threshold', '{"threshold":0.8}'::jsonb, 'a58cd791f61e56c2679c74b0263bb7fded555caae14437b2b1e68a9690c9d697', '2026-06-22T00:00:00.000Z', 'human:rathish-owner', true)
ON CONFLICT (config_version, key) DO NOTHING;

INSERT INTO recoup_customers (customer_id, name, profile)
VALUES
  ('CUST-GREENLEAF', 'Greenleaf Naturals', 'Regional wholesaler'),
  ('CUST-CRESTLINE', 'Crestline Grocery', 'Strategic retailer'),
  ('CUST-VALUMART', 'ValuMart Club', 'Club channel'),
  ('CUST-HARBOR', 'Harbor Foods', 'Foodservice distributor')
ON CONFLICT (customer_id) DO NOTHING;

INSERT INTO recoup_deduction_lines (
  line_id,
  scenario_id,
  customer_id,
  scenario_type,
  amount,
  verdict,
  routing,
  record_ids_json,
  rule_id,
  rule_input_json,
  period,
  event_id
)
VALUES
  ('S1-L1', 'S1', 'CUST-GREENLEAF', 'Damaged product, evidence received', 2700.00, 'valid', 'billing', '["S1-L1","PHOTO-CARRIER-1","INV-S1-1"]'::jsonb, 'damage-evidence-valid', '{"carrierReportReceived":true,"claimedAmount":"2700.00","damagedGoodsAmount":"2700.00","lineId":"S1-L1","period":"2026-06","photoEvidenceReceived":true,"recordIds":["S1-L1","PHOTO-CARRIER-1","INV-S1-1"],"ruleId":"damage-evidence-valid","salvageCreditAmount":"0.00"}'::jsonb, '2026-06', 'b93710c1944146881c247288c10cbcb1480416fd37c1c654d95723923086b562'),
  ('S1-L2', 'S1', 'CUST-GREENLEAF', 'Damaged product, evidence received', 2800.00, 'valid', 'billing', '["S1-L2","PHOTO-CARRIER-2","INV-S1-2"]'::jsonb, 'damage-evidence-valid', '{"carrierReportReceived":true,"claimedAmount":"2800.00","damagedGoodsAmount":"2800.00","lineId":"S1-L2","period":"2026-06","photoEvidenceReceived":true,"recordIds":["S1-L2","PHOTO-CARRIER-2","INV-S1-2"],"ruleId":"damage-evidence-valid","salvageCreditAmount":"0.00"}'::jsonb, '2026-06', '7d3e9134d9bc562cb15db246f22cdc94b7b019e1c6cf149cef9548590b136bd6'),
  ('S1-L3', 'S1', 'CUST-GREENLEAF', 'Damaged product, evidence received', 2700.00, 'valid', 'billing', '["S1-L3","PHOTO-CARRIER-3","INV-S1-3"]'::jsonb, 'damage-evidence-valid', '{"carrierReportReceived":true,"claimedAmount":"2700.00","damagedGoodsAmount":"2700.00","lineId":"S1-L3","period":"2026-06","photoEvidenceReceived":true,"recordIds":["S1-L3","PHOTO-CARRIER-3","INV-S1-3"],"ruleId":"damage-evidence-valid","salvageCreditAmount":"0.00"}'::jsonb, '2026-06', 'c651fb980433cabb052249dbaac0838e8e59e26301db042559c68527b7667f10'),
  ('S2-L1', 'S2', 'CUST-CRESTLINE', 'Valid promo billed at list', 7300.00, 'valid', 'billing', '["S2-L1","TPM-CONTRACT-1","INV-S2-1"]'::jsonb, 'promo-not-captured', '{"approvedPromoAccrual":"7300.00","approvedPromoExists":true,"capturedPromoCredit":"0.00","claimedAmount":"7300.00","invoiceBilledAtList":true,"lineId":"S2-L1","period":"2026-06","recordIds":["S2-L1","TPM-CONTRACT-1","INV-S2-1"],"ruleId":"promo-not-captured"}'::jsonb, '2026-06', '8eb9ececaa80a0a7e181c8ce85d7a6853348b8bc3544ec76be4a8b7f86d8dd54'),
  ('S2-L2', 'S2', 'CUST-CRESTLINE', 'Valid promo billed at list', 7300.00, 'valid', 'billing', '["S2-L2","TPM-CONTRACT-2","INV-S2-2"]'::jsonb, 'promo-not-captured', '{"approvedPromoAccrual":"7300.00","approvedPromoExists":true,"capturedPromoCredit":"0.00","claimedAmount":"7300.00","invoiceBilledAtList":true,"lineId":"S2-L2","period":"2026-06","recordIds":["S2-L2","TPM-CONTRACT-2","INV-S2-2"],"ruleId":"promo-not-captured"}'::jsonb, '2026-06', 'cf676fe718001c4a7753726b7cf4e9a0c7de968bc0231a003e5c648c017b634a'),
  ('S3-L1', 'S3', 'CUST-CRESTLINE', 'Shortage claim with full signed POD', 5300.00, 'invalid', 'recovery', '["S3-L1","POD-SIGNED-1","INV-S3-1"]'::jsonb, 'shortage-pod-mismatch', '{"allowedShortageAmount":"0.00","claimedAmount":"5300.00","claimedShortage":true,"lineId":"S3-L1","period":"2026-06","podSignedFullDelivery":true,"recordIds":["S3-L1","POD-SIGNED-1","INV-S3-1"],"ruleId":"shortage-pod-mismatch"}'::jsonb, '2026-06', 'be8029162c53c21854940e662917d598161c853fdde37b95555b991845801e22'),
  ('S3-L2', 'S3', 'CUST-CRESTLINE', 'Shortage claim with full signed POD', 5300.00, 'invalid', 'recovery', '["S3-L2","POD-SIGNED-2","INV-S3-2"]'::jsonb, 'shortage-pod-mismatch', '{"allowedShortageAmount":"0.00","claimedAmount":"5300.00","claimedShortage":true,"lineId":"S3-L2","period":"2026-06","podSignedFullDelivery":true,"recordIds":["S3-L2","POD-SIGNED-2","INV-S3-2"],"ruleId":"shortage-pod-mismatch"}'::jsonb, '2026-06', 'bda35b6b033cee3f3a25b68bcf38052ccf3c70e1f1b4bc80069f84d3a0354501'),
  ('S3-L3', 'S3', 'CUST-CRESTLINE', 'Shortage claim with full signed POD', 5350.00, 'invalid', 'recovery', '["S3-L3","POD-SIGNED-3","INV-S3-3"]'::jsonb, 'shortage-pod-mismatch', '{"allowedShortageAmount":"0.00","claimedAmount":"5350.00","claimedShortage":true,"lineId":"S3-L3","period":"2026-06","podSignedFullDelivery":true,"recordIds":["S3-L3","POD-SIGNED-3","INV-S3-3"],"ruleId":"shortage-pod-mismatch"}'::jsonb, '2026-06', '1792fc82c2d8614955e036481f3875daff804e83018410bd23fb6010e143912e'),
  ('S3-L4', 'S3', 'CUST-CRESTLINE', 'Shortage claim with full signed POD', 5350.00, 'invalid', 'recovery', '["S3-L4","POD-SIGNED-4","INV-S3-4"]'::jsonb, 'shortage-pod-mismatch', '{"allowedShortageAmount":"0.00","claimedAmount":"5350.00","claimedShortage":true,"lineId":"S3-L4","period":"2026-06","podSignedFullDelivery":true,"recordIds":["S3-L4","POD-SIGNED-4","INV-S3-4"],"ruleId":"shortage-pod-mismatch"}'::jsonb, '2026-06', '8b623299784d688142b93754af491bf63e398db65cd5a8f989be322fdb825de0'),
  ('S4-L1', 'S4', 'CUST-VALUMART', 'OTIF compliance fine valid per contract', 4900.00, 'valid', 'billing', '["S4-L1","SLA-CONTRACT-1","INV-S4-1"]'::jsonb, 'otif-fine-valid', '{"allowedFineAmount":"4900.00","claimedAmount":"4900.00","contractSlaAllowsFine":true,"lineId":"S4-L1","period":"2026-06","recordIds":["S4-L1","SLA-CONTRACT-1","INV-S4-1"],"ruleId":"otif-fine-valid","slaBreachConfirmed":true}'::jsonb, '2026-06', '99726cd7837802eb35809bfe581059d37671f8606b9a443e52e87dc233f6db8e'),
  ('S4-L2', 'S4', 'CUST-VALUMART', 'OTIF compliance fine valid per contract', 4900.00, 'valid', 'billing', '["S4-L2","SLA-CONTRACT-2","INV-S4-2"]'::jsonb, 'otif-fine-valid', '{"allowedFineAmount":"4900.00","claimedAmount":"4900.00","contractSlaAllowsFine":true,"lineId":"S4-L2","period":"2026-06","recordIds":["S4-L2","SLA-CONTRACT-2","INV-S4-2"],"ruleId":"otif-fine-valid","slaBreachConfirmed":true}'::jsonb, '2026-06', '11ecc0fb14e067ef5de69dff91a9ed3c85f33268dffd54ee5a95a4ddbc7fdd51'),
  ('S5-L1', 'S5', 'CUST-VALUMART', 'OTIF fine contradicted by 3PL POD timestamp', 4200.00, 'invalid', 'recovery', '["S5-L1","POD-TIMESTAMP-1","INV-S5-1"]'::jsonb, 'otif-timestamp-mismatch', '{"allowedFineAmount":"0.00","claimedAmount":"4200.00","lineId":"S5-L1","otifFineAssessed":true,"period":"2026-06","podTimestampOnTime":true,"recordIds":["S5-L1","POD-TIMESTAMP-1","INV-S5-1"],"ruleId":"otif-timestamp-mismatch"}'::jsonb, '2026-06', '98459f24ded97a316bb30b6963d9fd795bc184019c55987a76a7c1b66867a57d'),
  ('S5-L2', 'S5', 'CUST-VALUMART', 'OTIF fine contradicted by 3PL POD timestamp', 4250.00, 'invalid', 'recovery', '["S5-L2","POD-TIMESTAMP-2","INV-S5-2"]'::jsonb, 'otif-timestamp-mismatch', '{"allowedFineAmount":"0.00","claimedAmount":"4250.00","lineId":"S5-L2","otifFineAssessed":true,"period":"2026-06","podTimestampOnTime":true,"recordIds":["S5-L2","POD-TIMESTAMP-2","INV-S5-2"],"ruleId":"otif-timestamp-mismatch"}'::jsonb, '2026-06', '31dc11c694b94a7d360f0195b4998f3f8c48de2028cc3b99b3239cb59b66165e'),
  ('S5-L3', 'S5', 'CUST-VALUMART', 'OTIF fine contradicted by 3PL POD timestamp', 4250.00, 'invalid', 'recovery', '["S5-L3","POD-TIMESTAMP-3","INV-S5-3"]'::jsonb, 'otif-timestamp-mismatch', '{"allowedFineAmount":"0.00","claimedAmount":"4250.00","lineId":"S5-L3","otifFineAssessed":true,"period":"2026-06","podTimestampOnTime":true,"recordIds":["S5-L3","POD-TIMESTAMP-3","INV-S5-3"],"ruleId":"otif-timestamp-mismatch"}'::jsonb, '2026-06', '635908534b6d987b35b66d5a7267a8358eecf97f5e60abc66da6931f4c8e7033'),
  ('S6-L1', 'S6', 'CUST-CRESTLINE', 'Pricing chargeback below contracted price', 9200.00, 'invalid', 'recovery', '["S6-L1","PRICE-CLAUSE-1","INV-S6-1"]'::jsonb, 'pricing-below-contract', '{"actualPaidAmount":"0.00","claimedAmount":"9200.00","contractPriceAvailable":true,"contractedUnitPrice":"9200.00","deductedBelowContractPrice":true,"deliveredQuantity":"1","lineId":"S6-L1","period":"2026-06","recordIds":["S6-L1","PRICE-CLAUSE-1","INV-S6-1"],"ruleId":"pricing-below-contract"}'::jsonb, '2026-06', '7574a2765629be3bd882b41d8f8afb50aa8c73ab8482ace9a4ea1657c9e8b751'),
  ('S6-L2', 'S6', 'CUST-CRESTLINE', 'Pricing chargeback below contracted price', 9200.00, 'invalid', 'recovery', '["S6-L2","PRICE-CLAUSE-2","INV-S6-2"]'::jsonb, 'pricing-below-contract', '{"actualPaidAmount":"0.00","claimedAmount":"9200.00","contractPriceAvailable":true,"contractedUnitPrice":"9200.00","deductedBelowContractPrice":true,"deliveredQuantity":"1","lineId":"S6-L2","period":"2026-06","recordIds":["S6-L2","PRICE-CLAUSE-2","INV-S6-2"],"ruleId":"pricing-below-contract"}'::jsonb, '2026-06', 'e1b0c3aabea6d6f10f8188ea66e659d9f46f988a2f827857b3f5062618d18cf9'),
  ('S7-L1', 'S7', 'CUST-HARBOR', 'Promo overclaim above approved TPM accrual', 7900.00, 'partial', 'recovery', '["S7-L1","TPM-ACCRUAL-1","INV-S7-1"]'::jsonb, 'promo-overclaim', '{"approvedAccrual":"0.00","approvedAccrualExceeded":true,"claimedAllowance":"7900.00","claimedAmount":"7900.00","lineId":"S7-L1","period":"2026-06","recordIds":["S7-L1","TPM-ACCRUAL-1","INV-S7-1"],"ruleId":"promo-overclaim"}'::jsonb, '2026-06', '73f0189b7fa54b413c5c587f94b09dbb6c66a296fa214faf8387d901fe085990'),
  ('S7-L2', 'S7', 'CUST-HARBOR', 'Promo overclaim above approved TPM accrual', 8000.00, 'partial', 'recovery', '["S7-L2","TPM-ACCRUAL-2","INV-S7-2"]'::jsonb, 'promo-overclaim', '{"approvedAccrual":"0.00","approvedAccrualExceeded":true,"claimedAllowance":"8000.00","claimedAmount":"8000.00","lineId":"S7-L2","period":"2026-06","recordIds":["S7-L2","TPM-ACCRUAL-2","INV-S7-2"],"ruleId":"promo-overclaim"}'::jsonb, '2026-06', '90731c0092971c1cef98b0f63bc6bda2af5be93a879f6ed6eae3716fa5da8d9c'),
  ('S8-L1', 'S8', 'CUST-HARBOR', 'Duplicate already-credited deduction', 5750.00, 'invalid', 'recovery', '["S8-L1","CREDIT-MEMO-1","INV-S8-1"]'::jsonb, 'duplicate-credit', '{"alreadyCredited":true,"claimedAmount":"5750.00","lineId":"S8-L1","period":"2026-06","priorCreditAmount":"5750.00","recordIds":["S8-L1","CREDIT-MEMO-1","INV-S8-1"],"ruleId":"duplicate-credit"}'::jsonb, '2026-06', 'fc44ba51b4e4096089bb76c9a09275878d0628b5c5b1b915d196e6b29176472c'),
  ('S8-L2', 'S8', 'CUST-HARBOR', 'Duplicate already-credited deduction', 5750.00, 'invalid', 'recovery', '["S8-L2","CREDIT-MEMO-2","INV-S8-2"]'::jsonb, 'duplicate-credit', '{"alreadyCredited":true,"claimedAmount":"5750.00","lineId":"S8-L2","period":"2026-06","priorCreditAmount":"5750.00","recordIds":["S8-L2","CREDIT-MEMO-2","INV-S8-2"],"ruleId":"duplicate-credit"}'::jsonb, '2026-06', 'db67bb45bd845fe2fe2a101a43e9287485f1aa54925d004c406ae3c988e9276b')
ON CONFLICT (line_id) DO NOTHING;

INSERT INTO customers (
  customer_id,
  r_score_component_scores_json,
  customer_name,
  segment,
  strategic_value,
  credit_limit,
  revenue_forecast_12mo
)
VALUES
  ('USCU_S04', '{"agingConcentration":60,"disputeRate":71,"dsoAdp":70,"overLimitFrequency":70}'::jsonb, 'Harbor Foods', 'Foodservice Distributor', 'Medium', 500000.0, 9000000.0),
  ('USCU_L10', '{"agingConcentration":15,"disputeRate":73.1,"dsoAdp":10,"overLimitFrequency":0}'::jsonb, 'Crestline Grocery', 'Strategic Retail', 'High', 10000000.0, 48000000.0),
  ('USCU_S07', '{"agingConcentration":20,"disputeRate":56.4,"dsoAdp":15,"overLimitFrequency":0}'::jsonb, 'ValuMart Club', 'Club', 'High', 1500000.0, 22000000.0),
  ('USCU_S03', '{"agingConcentration":25,"disputeRate":0,"dsoAdp":20,"overLimitFrequency":0}'::jsonb, 'Greenleaf Naturals', 'Regional Wholesaler', 'Low', 50000.0, 3500000.0)
ON CONFLICT (customer_id) DO UPDATE SET
  r_score_component_scores_json = EXCLUDED.r_score_component_scores_json,
  customer_name = EXCLUDED.customer_name,
  segment = EXCLUDED.segment,
  strategic_value = EXCLUDED.strategic_value,
  credit_limit = EXCLUDED.credit_limit,
  revenue_forecast_12mo = EXCLUDED.revenue_forecast_12mo,
  updated_at = now();

ALTER TABLE recoup_app_principals ENABLE ROW LEVEL SECURITY;
ALTER TABLE recoup_app_principals FORCE ROW LEVEL SECURITY;
ALTER TABLE recoup_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE recoup_config FORCE ROW LEVEL SECURITY;
ALTER TABLE recoup_audit_chain ENABLE ROW LEVEL SECURITY;
ALTER TABLE recoup_audit_chain FORCE ROW LEVEL SECURITY;
ALTER TABLE recoup_customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE recoup_customers FORCE ROW LEVEL SECURITY;
ALTER TABLE recoup_deduction_lines ENABLE ROW LEVEL SECURITY;
ALTER TABLE recoup_deduction_lines FORCE ROW LEVEL SECURITY;
ALTER TABLE recoup_src_bureau ENABLE ROW LEVEL SECURITY;
ALTER TABLE recoup_src_bureau FORCE ROW LEVEL SECURITY;
ALTER TABLE recoup_src_docs ENABLE ROW LEVEL SECURITY;
ALTER TABLE recoup_src_docs FORCE ROW LEVEL SECURITY;
ALTER TABLE recoup_src_remittance ENABLE ROW LEVEL SECURITY;
ALTER TABLE recoup_src_remittance FORCE ROW LEVEL SECURITY;
ALTER TABLE recoup_src_sap ENABLE ROW LEVEL SECURITY;
ALTER TABLE recoup_src_sap FORCE ROW LEVEL SECURITY;
ALTER TABLE recoup_src_tpm ENABLE ROW LEVEL SECURITY;
ALTER TABLE recoup_src_tpm FORCE ROW LEVEL SECURITY;
ALTER TABLE recoup_source_health_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE recoup_source_health_snapshots FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS recoup_source_health_snapshots_service_role_select ON recoup_source_health_snapshots;
DROP POLICY IF EXISTS recoup_source_health_snapshots_service_role_insert ON recoup_source_health_snapshots;
DROP POLICY IF EXISTS recoup_source_health_snapshots_service_role_update ON recoup_source_health_snapshots;
CREATE POLICY recoup_source_health_snapshots_service_role_select
  ON recoup_source_health_snapshots
  FOR SELECT TO service_role USING (true);
CREATE POLICY recoup_source_health_snapshots_service_role_insert
  ON recoup_source_health_snapshots
  FOR INSERT TO service_role WITH CHECK (true);
CREATE POLICY recoup_source_health_snapshots_service_role_update
  ON recoup_source_health_snapshots
  FOR UPDATE TO service_role USING (true) WITH CHECK (true);
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE customers FORCE ROW LEVEL SECURITY;
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments FORCE ROW LEVEL SECURITY;
ALTER TABLE pod_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE pod_records FORCE ROW LEVEL SECURITY;
ALTER TABLE promotions ENABLE ROW LEVEL SECURITY;
ALTER TABLE promotions FORCE ROW LEVEL SECURITY;
ALTER TABLE contracts ENABLE ROW LEVEL SECURITY;
ALTER TABLE contracts FORCE ROW LEVEL SECURITY;
ALTER TABLE carrier_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE carrier_reports FORCE ROW LEVEL SECURITY;
ALTER TABLE damage_photos ENABLE ROW LEVEL SECURITY;
ALTER TABLE damage_photos FORCE ROW LEVEL SECURITY;
ALTER TABLE bureau_alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE bureau_alerts FORCE ROW LEVEL SECURITY;
ALTER TABLE remittance_headers ENABLE ROW LEVEL SECURITY;
ALTER TABLE remittance_headers FORCE ROW LEVEL SECURITY;
ALTER TABLE remittance_lines ENABLE ROW LEVEL SECURITY;
ALTER TABLE remittance_lines FORCE ROW LEVEL SECURITY;
ALTER TABLE deductions_backlog ENABLE ROW LEVEL SECURITY;
ALTER TABLE deductions_backlog FORCE ROW LEVEL SECURITY;
ALTER TABLE billing_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE billing_requests FORCE ROW LEVEL SECURITY;
ALTER TABLE recovery_packages ENABLE ROW LEVEL SECURITY;
ALTER TABLE recovery_packages FORCE ROW LEVEL SECURITY;
ALTER TABLE credit_decisions ENABLE ROW LEVEL SECURITY;
ALTER TABLE credit_decisions FORCE ROW LEVEL SECURITY;
ALTER TABLE immutable_audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE immutable_audit_log FORCE ROW LEVEL SECURITY;
ALTER TABLE recoup_memory_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE recoup_memory_records FORCE ROW LEVEL SECURITY;
